namespace: prediction

backend:
  name: backend
  replicas: 2
  image:
    repository: prediction-backend
    tag: local
    pullPolicy: IfNotPresent
  port: 8000
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 60

frontend:
  name: frontend
  replicas: 1
  image:
    repository: prediction-frontend
    tag: local
    pullPolicy: IfNotPresent
  port: 80
  nodePort: 30007
