namespace: prediction

backend:
  name: backend
  replicas: 2
  image:
    repository: ghcr.io/jasvendrasingh/prediction-backend
    tag: latest
    pullPolicy: Always
  port: 8000
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 60

frontend:
  name: frontend
  replicas: 1
  image:
    repository: ghcr.io/jasvendrasingh/prediction-frontend
    tag: latest
    pullPolicy: Always
  port: 80
  nodePort: 30007
